### ISSUE TITLE
New Interface

### ISSUE THREAD

**Issue by harrypotts1** [eric-wieser/caius-meal-booking-extension#10]
Hi Eric,

The mealbooking extension is no longer working with the new interface. There is no summary tab at the top and the https://www.mealbookings.cai.cam.ac.uk/menus link returns a 404 not found error. I don't know whether it is possible for this feature to return but I would absolutely love it to do so as I found this extension so useful.

Best wishes,
Harry

**Comment by eric-wieser** [comment]
I don't think there's anything I can do here. I'm no longer at the university, so cannot see the new interface or use it to test against.

Out of curiousity - can you post a screenshot of the new interface here?

**Comment by eric-wieser** [comment]
Fixed in 0.2.1, hopefully
